resolver: lts-18.14
compiler: ghc-8.10.7

packages:
- .

extra-deps:
  - text-1.2.4.1
  - bytestring-0.10.12.0
  - aeson-1.5.6.0
  - http-types-0.12.3
  - http-client-0.6.4.1
  - http-client-tls-0.3.5.3
  - time-1.9.3
  - unordered-containers-0.2.14.0
  - vector-0.12.3.1
